export interface SceneControl {
  name: string
  label: string
  title: string
  description: string
  start: number
  end: number
}

export interface ModuleData {
  id: string
  title: string
  scenes: SceneControl[]
}

export const MODULE_DATA: Record<string, ModuleData> = {
  module1: {
    id: "module1",
    title: "Deployment & Onboarding",
    scenes: [
      {
        name: "registration",
        label: "Employee Data Registration",
        title: "Employee Data Registration",
        description: "The deployment process begins with companies submitting their active employees list. Organizations may also integrate their existing HRMS with the FOS platform through secure API enabling real-time data synchronization. The FOS team uploads and validates the data to ensure system readiness.",
        start: 0,
        end: 22,
      },
      {
        name: "fos_ids",
        label: "Automatic FOS IDs Generation",
        title: "Automatic FOS IDs Generation",
        description: "Each employee is assigned a unique FOS ID which is mapped with the employee's CNIC for accurate identification and ease of access during grievance registration.",
        start: 22,
        end: 42,
      },
      {
        name: "sms",
        label: "SMS Distribution of FOS IDs",
        title: "SMS Distribution of FOS IDs",
        description: "FOS IDs are sent directly to employees via the FOS SMS Service ensuring immediate accessibility even for workers without smartphones or internet access.",
        start: 42,
        end: 58,
      },
      {
        name: "cards",
        label: "Personalized FOS Awareness Cards",
        title: "Personalized FOS Awareness Cards",
        description: "Personalized FOS Grievance Awareness Cards are designed for every employee. In addition to written instructions, each card includes a QR code that leads to a video guide explaining grievance reporting channels and registration process. These cards are printed and distributed within the facility to maximize awareness and ease of use.",
        start: 58,
        end: 83,
      },
      {
        name: "officers",
        label: "Appointment of Investigation Officer(s)",
        title: "Appointment of Investigation Officer(s)",
        description: "The company nominates its employee as Investigation Officer (IO) who is responsible for grievance resolutions and documentation. Multiple Investigation Officers (IOs) may be appointed based on unit, gender or complaint category.",
        start: 83,
        end: 101,
      },
      {
        name: "onsite",
        label: "On-Site Deployment & Awareness Sessions",
        title: "On-Site Deployment & Awareness Sessions",
        description: "The FOS Team visits the facility to conduct comprehensive deployment and awareness sessions, educating employees and workers on grievance reporting channels and system functionality while providing management with a structured walkthrough of dashboards, remediation responsibilities and reporting protocols.",
        start: 101,
        end: 120,
      },
      {
        name: "training",
        label: "IO Training & Portal Activation",
        title: "Investigation Officer-IO Training & Portal Activation",
        description: "Investigation Officers receive secure login credentials to document Root Cause Analysis (RCA), Corrective and Preventive Actions (CAPA) and supporting evidence. The FOS Team provides dedicated training on RCA validation, CAPA documentation, evidence uploading and best-practice grievance remediation.",
        start: 120,
        end: 155,
      },
    ],
  },
  module2: {
    id: "module2",
    title: "Complaint Intake & Registration",
    scenes: [
      {
        name: "channels",
        label: "Grievance Reporting Channels",
        title: "Grievance Reporting Channels",
        description: "FOS provides a multi-channel reporting ecosystem—Toll-Free Hotline, SMS/WhatsApp, Email, Online Form and Mobile App—ensuring all employees regardless of literacy or device access, can report concerns confidentially and without barriers.",
        start: 0,
        end: 28,
      },
      {
        name: "assisted",
        label: "Assisted Complaint Filing",
        title: "Assisted Complaint Filing",
        description: "When complaints are received through phone, SMS, WhatsApp or email, trained FOS Grievance Officers conduct structured interviews, verify information, request evidence where applicable and digitally submit the complaint on behalf of the worker, ensuring inclusivity for non-digital users.",
        start: 28,
        end: 57,
      },
      {
        name: "anonymous",
        label: "Anonymous Complaint Option",
        title: "Anonymous Complaint Option",
        description: "Employees may register complaints anonymously through any reporting channel. The system masks identifying information from factory management and assigns an anonymous tracking ID, ensuring protection from retaliation and enabling safe disclosure of sensitive concerns such as harassment, discrimination or abuse.",
        start: 57,
        end: 77,
      },
      {
        name: "review",
        label: "Complaint Review & Approval",
        title: "Complaint Review & Approval",
        description: "Every incoming submission—whether self-filed or assisted—is reviewed by FOS Team to ensure accuracy, proper category mapping and completeness. This step guarantees high-quality data entry and compliance with HRDD reporting standards.",
        start: 77,
        end: 95,
      },
      {
        name: "ticket",
        label: "Ticket Number Generation",
        title: "Ticket Number Generation",
        description: "Once verified, each complaint is assigned a unique system-generated ticket ID, enabling traceability, audit-ready documentation and transparent end-to-end tracking throughout the grievance lifecycle.",
        start: 95,
        end: 101,
      },
      {
        name: "sms_notification",
        label: "SMS Notification to Complainant",
        title: "SMS Notification to Complainant",
        description: "The complainant receives an automated SMS containing the ticket number, category and confirmation of successful registration, ensuring immediate acknowledgment and enhancing trust in the system.",
        start: 101,
        end: 113,
      },
      {
        name: "io_notification",
        label: "IO Notification & Assignment",
        title: "IO Notification & Assignment",
        description: "The relevant Investigation Officer (IO) is automatically notified via the FOS mobile app and system-generated email alerts. The complaint appears in the IO-Portal for timely action, maintaining workflow efficiency.",
        start: 113,
        end: 135,
      },
    ],
  },
  module3: {
    id: "module3",
    title: "Investigation-Remediation-Satisfaction Framework",
    scenes: [
      {
        name: "activation",
        label: "Case Activation",
        title: "Case Activation",
        description: "Once a complaint is received, it appears in the IO-Portal under Unprocessed category. The Investigation Officer (IO) reviews the initial complaint details and formally changes its status to 'In-Process.' This initiates the investigation workflow and activates system-level tracking for timely remediation.",
        start: 0,
        end: 26,
      },
      {
        name: "rca",
        label: "Root Cause Analysis (RCA) Entry",
        title: "Root Cause Analysis (RCA) Entry",
        description: "The IO evaluates the complaint to determine whether it is Valid, Partially Valid or Invalid based on evidence, worker interviews, production floor checks and cross-verification with attendance, payroll or security records where applicable. The justification, along with the defined CAPA deadline is recorded in the Root Cause Analysis (RCA).",
        start: 26,
        end: 55,
      },
      {
        name: "capa",
        label: "Corrective and Preventive Action (CAPA) Development",
        title: "Corrective and Preventive Action (CAPA) Development",
        description: "For valid or partially valid complaints, the IO develops a comprehensive Corrective and Preventive Action (CAPA) plan. This includes identifying the immediate remedies required to resolve the issue and the long-term preventive measures needed to avoid recurrence. The IO assigns responsibilities, sets realistic execution deadlines and outlines the steps that internal teams must follow. All CAPA details are entered in the IO-Portal, which subsequently triggers system notifications and deadline reminders.",
        start: 55,
        end: 76,
      },
      {
        name: "evidence",
        label: "Evidence Submission & Documentation",
        title: "Evidence Submission & Documentation",
        description: "After implementing the necessary actions, the IO compiles and uploads all supporting evidence to verify the investigation and CAPA completion. This may include images, written statements, committee notes, records of repairs or adjustments or updated policy documents. All submissions are time-stamped and stored securely in the system, forming a complete and compliant documentation trail aligned with HRDD requirements.",
        start: 76,
        end: 98,
      },
      {
        name: "route",
        label: "Complaint Route Feature",
        title: "Complaint Route Feature",
        description: "The IO has option to route complaint via email directly from the system to relevant internal stakeholders for consultation on Root Cause Analysis (RCA) and Corrective and Preventive Actions (CAPA). This feature enables cross-functional collaboration and supports coordinated and timely resolution of complex cases.",
        start: 98,
        end: 111,
      },
      {
        name: "verification",
        label: "Worker Interview for Independent Verification",
        title: "Worker Interview for Independent Verification",
        description: "Once a complaint is submitted, FOS Grievance Officers independently contact the complainant to verify the factory's resolution. During this call, the worker is informed about the actions taken and their satisfaction with the outcome is assessed. This step ensures impartiality, as independent verification by FOS eliminates any conflict of interest and confirms that the resolution genuinely addresses the worker's concern.",
        start: 111,
        end: 128,
      },
      {
        name: "bounceback",
        label: "Bounce-Back Mechanism (If Not Satisfied)",
        title: "Bounce-Back Mechanism (If Not Satisfied)",
        description: "If the complainant is not satisfied or raises concerns about incomplete or ineffective remediation, the complaint is returned 'bounced back' to the IO. The IO must re-evaluate RCA, update CAPA actions and provide additional evidence before resubmission. This ensures issues cannot be prematurely closed and reinforces accountability.",
        start: 128,
        end: 148,
      },
      {
        name: "escalation",
        label: "Escalation Mechanism & Senior Management Engagement",
        title: "Escalation Mechanism & Senior Management Engagement",
        description: "An escalation mechanism can be configured within the system to automatically trigger when defined resolution timelines are exceeded or when complaints are bounced back. This feature enables timely involvement of senior management or designated escalation authorities, strengthening accountability and ensuring effective resolution of high-risk or delayed cases.",
        start: 148,
        end: 161,
      },
      {
        name: "closure",
        label: "FOS Closure Feedback & Recordkeeping",
        title: "FOS Closure Feedback & Recordkeeping",
        description: "Once the complainant confirms full satisfaction, FOS team closes the complaint in the system and records detailed closure feedback. This includes a summary of the conversation, the worker's confirmation and any additional notes relevant to future monitoring or reporting. All closure data is preserved in the system's digital archive, contributing to grievance trend analysis, HRDD indicators and long-term risk prevention insights.",
        start: 161,
        end: 177,
      },
    ],
  },
  module4: {
    id: "module4",
    title: "Digital Surveys",
    scenes: [
      {
        name: "initiation",
        label: "Survey Initiation & Configuration",
        title: "Survey Initiation & Configuration",
        description: "The company can initiate multiple digital surveys directly from the system by defining the Survey Title, Description and visibility period. Surveys can be launched in multiple languages, allowing employees to view and respond in their native language, thereby improving accessibility, participation rates and response accuracy.",
        start: 0,
        end: 26,
      },
      {
        name: "targeting",
        label: "Participants Selection & Targeting",
        title: "Participants Selection & Targeting",
        description: "Survey participants can be precisely selected based on organizational attributes such as designation, department, unit or gender. The FOS system also allows random sampling using CNIC numbers or company employee IDs, enabling statistically representative surveys while maintaining data integrity.",
        start: 26,
        end: 46,
      },
      {
        name: "notifications",
        label: "Survey Launch Notifications",
        title: "Survey Launch Notifications",
        description: "Once launched, selected employees receive automated survey invitations via the FOS SMS Service. The message includes a direct survey link for employees who do not have the mobile app installed, ensuring timely engagement and easy access for all participants.",
        start: 46,
        end: 63,
      },
      {
        name: "responses",
        label: "Confidential Response Submission",
        title: "Confidential Response Submission",
        description: "Employees submit their responses directly within the mobile app at their convenience. Responses are automatically linked to the survey configuration with anonymity to encourage honest and unbiased feedback.",
        start: 63,
        end: 75,
      },
      {
        name: "reports",
        label: "Real-time Survey Report Compilation",
        title: "Real-time Survey Report Compilation",
        description: "As responses are submitted, an automated real-time report is generated and made available within the dashboard. Management can view response rates, summary statistics, charts and trends to support informed decision-making.",
        start: 75,
        end: 91,
      },
      {
        name: "ai",
        label: "Advanced AI Analysis for Open-Ended Feedbacks",
        title: "Advanced AI Analysis for Open-Ended Feedbacks",
        description: "For open-ended text responses, the system applies AI-based analysis to automatically interpret employee feedback. Responses are analyzed and grouped by sentiment—such as positive, neutral or negative—and presented in a reader-friendly format within the dashboard.",
        start: 91,
        end: 115,
      },
    ],
  },
  module5: {
    id: "module5",
    title: "Dashboards & Risk Insights",
    scenes: [
      {
        name: "architecture",
        label: "Multi-Layer Dashboard Architecture",
        title: "Multi-Layer Dashboard Architecture",
        description: "The dashboard structure is designed with multiple layers, allowing separate dashboards to be configured for individual sites, business units or different management levels. This ensures that each stakeholder—such as site management, senior leadership or compliance teams—has access to relevant insights based on their role and responsibilities.",
        start: 0,
        end: 24,
      },
      {
        name: "filters",
        label: "Location & Date Filters",
        title: "Location & Date Filters",
        description: "The dashboard allows users to filter grievance data by site, including supplier-wise, department-wise or branch-wise views along with flexible date-range filters. This enables management to analyze grievances for specific locations or time periods, compare performance across sites and identify emerging or recurring risks with precision.",
        start: 24,
        end: 40,
      },
      {
        name: "overview",
        label: "Grievances Overview & Breakdowns",
        title: "Grievances Overview & Breakdowns",
        description: "This dashboard gives a full picture of total complaints, count anonymous complaints, completed cases and those still in process. It also presents status indicators such as bounced or unclosed complaints, helping assess the effectiveness and quality of grievance handling. In addition, date-wise trend charts and gender-wise breakdowns support deeper analysis of grievance patterns. A separate section provided general employee suggestions or feedbacks, while the category-wise distribution highlights key HRDD risk areas, enabling management to identify priorities and direct corrective actions where they are most needed.",
        start: 40,
        end: 88,
      },
      {
        name: "counseling",
        label: "Counseling Sessions Breakdown",
        title: "Counseling Sessions Breakdown",
        description: "This section highlights cases where the FOS team provided direct counseling and guidance to workers. Through timely discussion and support, the worker's concern was addressed satisfactorily and no formal grievance was required to be launched.",
        start: 88,
        end: 102,
      },
      {
        name: "performance",
        label: "Investigation Officer IO Performance Tracking",
        title: "Investigation Officer IO Performance Tracking",
        description: "This section tracks the time taken by the Investigation officer (IO) to resolve individual complaints. By showing how many cases are resolved within the same day or defined time slabs, it provides clear insight into IO performance and overall effectiveness of grievance handling processes.",
        start: 102,
        end: 114,
      },
      {
        name: "drilldown",
        label: "Drill-Down Lists with AI Summaries",
        title: "Drill-Down Lists with AI Summaries",
        description: "Each dashboard statistic is interactive and clickable allowing users to view the list of complaint ticket numbers linked to that specific metric. For quick review, the system displays an AI-generated summary of the complaint along with a separate summary of the RCA and CAPA for each ticket. By clicking further on any ticket number, users can access the complete complaint timeline including all actions, evidence and status changes for detailed case oversight.",
        start: 114,
        end: 137,
      },
      {
        name: "scores",
        label: "Worker Happiness & Safety Scores",
        title: "Worker Happiness & Safety Scores",
        description: "These statistically generated scores benchmark worker happiness and workplace safety based on grievance data, counseling outcomes and verification feedback. They provide a clear reference point to track improvements over time, compare performance across sites and assess the impact of corrective and preventive actions.",
        start: 137,
        end: 155,
      },
      {
        name: "surveys",
        label: "Multi-Purpose Survey Reports",
        title: "Multi-Purpose Survey Reports",
        description: "This section consolidates all completed surveys and reports in one place. The archived records support trend analysis, audit requirements and continuous monitoring of workforce conditions over time.",
        start: 155,
        end: 165,
      },
    ],
  },
}