export interface SceneControl {
  name: string
  label: string
  title: string
  description: string
  start: number
  end: number
}

export interface ModuleData {
  id: string
  title: string
  scenes: SceneControl[]
}

export const MODULE_DATA: Record<string, ModuleData> = {
  module1: {
    id: "module1",
    title: "Deployment & Onboarding",
    scenes: [
      {
        name: "hero",
        label: "Overview",
        title: "Deployment & Onboarding",
        description: "Smooth rollout to empower every employee from day one.",
        start: 0,
        end: 2,
      },
      {
        name: "upload",
        label: "Employee Data Registration",
        title: "Employee Data Registration",
        description: "The deployment process begins with companies sharing active employee lists or integrating existing HRMS via secure APIs. The FOS team uploads and validates every record.",
        start: 2,
        end: 22,
      },
      {
        name: "sms",
        label: "FOS IDs & Accessibility",
        title: "FOS IDs & Accessibility",
        description: "System generates unique FOS IDs mapped to CNICs. These are sent via SMS service, ensuring immediate access even without smartphones or internet.",
        start: 22,
        end: 58,
      },
      {
        name: "card",
        label: "Awareness Cards",
        title: "Personalized FOS Awareness Cards",
        description: "Personalized cards include IDs, instructions, reporting channels, and QR codes for video guides to maximize awareness on the factory floor.",
        start: 58,
        end: 83,
      },
      {
        name: "officers",
        label: "Appointment of IOs",
        title: "Appointment of Investigation Officer(s)",
        description: "Companies appoint internal IOs by unit, gender, or category to manage grievance resolution and documentation.",
        start: 83,
        end: 101,
      },
      {
        name: "training",
        label: "On-Site Training",
        title: "On-Site Deployment & Awareness Sessions",
        description: "FOS Team visits the facility for complete on-site sessions: training workers on reporting, briefing management on dashboards, and walking everyone through the system.",
        start: 101,
        end: 120,
      },
      {
        name: "portal",
        label: "IO Portal Access",
        title: "Secured IO Portal Access",
        description: "Investigation Officers receive secure portal access to document RCA, CAPA, and upload evidence.",
        start: 120,
        end: 134,
      },
      {
        name: "io_training",
        label: "IO Skills Training",
        title: "Investigation Officer Training",
        description: "FOS team trains IOs on validating complaints, building corrective plans, uploading evidence, and closing cases effectively.",
        start: 134,
        end: 149,
      },
      {
        name: "closing",
        label: "Conclusion",
        title: "System Ready",
        description: "Ensures your grievance management system is fully functional from day one.",
        start: 149,
        end: 152,
      },
    ],
  },
  module2: {
    id: "module2",
    title: "Complaint Intake & Registration",
    scenes: [
      {
        name: "intro",
        label: "Overview",
        title: "Complaint Intake & Registration",
        description: "Multiple grievance reporting channels—confidential, accessible, and worker-friendly.",
        start: 0,
        end: 5,
      },
      {
        name: "omnichannel",
        label: "Grievance Reporting Channels",
        title: "Grievance Reporting Channels",
        description: "FOS provides a multi-channel reporting ecosystem—Toll-Free Hotline, SMS/WhatsApp, Email, Online Form, and Mobile App—ensuring all employees, regardless of literacy or device access, can report concerns confidentially and without barriers.",
        start: 5,
        end: 28,
      },
      {
        name: "assisted",
        label: "Assisted Complaint Filing",
        title: "Assisted Complaint Filing",
        description: "When complaints are received through phone, SMS, WhatsApp, or email, trained FOS Grievance Officers conduct structured interviews, verify information, request evidence where applicable, and digitally submit the complaint on behalf of the worker.",
        start: 28,
        end: 57,
      },
      {
        name: "anonymity",
        label: "Anonymous Complaint Option",
        title: "Anonymous Complaint Option",
        description: "Employees may register complaints anonymously through any reporting channel. The system masks identifying information from factory management and assigns an anonymous tracking ID.",
        start: 57,
        end: 77,
      },
      {
        name: "review",
        label: "Complaint Review & Approval",
        title: "Complaint Review & Approval",
        description: "Every incoming submission—whether self-filed or assisted—is reviewed by FOS to ensure accuracy, proper category mapping and completeness.",
        start: 77,
        end: 95,
      },
      {
        name: "ticket",
        label: "Ticket Number Generation",
        title: "Ticket Number System",
        description: "Once verified, each complaint is assigned a unique system-generated ticket ID, shared with the worker via SMS for tracking.",
        start: 95,
        end: 113,
      },
      {
        name: "notification",
        label: "IO Notification & Assignment",
        title: "IO Notification & Assignment",
        description: "The relevant Investigation Officer (IO) is automatically notified via the IO mobile app and system-generated email alerts.",
        start: 113,
        end: 132,
      },
    ],
  },
  module3: {
    id: "module3",
    title: "Investigation-Remediation-Satisfaction Framework",
    scenes: [
      {
        name: "intro",
        label: "Overview",
        title: "Investigation-Remediation-Satisfaction Framework",
        description: "Systematic resolution workflows with verified employee satisfaction.",
        start: 0,
        end: 12.24,
      },
      {
        name: "timeline",
        label: "Case Activation",
        title: "Case Activation",
        description: "Once a complaint is received, it appears in the IO-Portal under Unprocessed. The Investigation Officer (IO) reviews the initial complaint details, selects the case, and formally changes its status to 'In-Process.' This initiates the investigation workflow and activates system-level SLA tracking for timely remediation.",
        start: 12.24,
        end: 23.76,
      },
      {
        name: "validity",
        label: "Validity Assessment",
        title: "Validity Assessment",
        description: "The IO evaluates the complaint to determine whether it is Valid, Partially Valid, or Invalid. This assessment is based on evidence, worker interviews, production floor checks, and cross-verification with attendance, payroll, or security records where applicable. A justification is entered into Root Cause Analysis RCA, creating a transparent audit trail.",
        start: 23.76,
        end: 37.92,
      },
      {
        name: "rootCause",
        label: "Root Cause Analysis",
        title: "Root Cause Analysis",
        description: "A justification is entered into Root Cause Analysis (RCA), creating a transparent audit trail for the validity assessment.",
        start: 37.92,
        end: 51.32,
      },
      {
        name: "capa",
        label: "CAPA Development",
        title: "CAPA Development",
        description: "For valid or partially valid complaints, the IO develops a comprehensive Corrective and Preventive Action (CAPA) plan. This includes identifying the immediate remedies required to resolve the issue and the long-term preventive measures needed to avoid recurrence. The IO assigns responsibilities, sets realistic execution deadlines, and outlines the steps that internal teams must follow.",
        start: 51.32,
        end: 70.88,
      },
      {
        name: "evidence",
        label: "Evidence Submission & Documentation",
        title: "Evidence Submission & Documentation",
        description: "After implementing the necessary actions, the IO compiles and uploads all supporting evidence to substantiate the investigation and CAPA completion. This may include photographs, written statements, committee notes, records of repairs or adjustments, or updated policy documents. All submissions are time-stamped and stored securely in the system, forming a complete and compliant documentation trail aligned with HRDD and audit requirements.",
        start: 70.88,
        end: 80.04,
      },
      {
        name: "verification",
        label: "Worker Interview for Independent Verification",
        title: "Worker Interview for Independent Verification",
        description: "FOS Grievance Officers independently contact the complainant to verify the factory's resolution. During this call, the worker is informed about the actions taken, and their satisfaction with the outcome is assessed. This step ensures impartiality, as independent verification by FOS eliminates any conflict of interest and confirms that the resolution genuinely addresses the worker's concern.",
        start: 80.04,
        end: 99.12,
      },
      {
        name: "rework",
        label: "Bounce-Back Mechanism",
        title: "Bounce-Back Mechanism",
        description: "If the complainant is not satisfied or raises concerns about incomplete or ineffective remediation, the complaint is returned ('bounced back') to the IO. The IO must re-evaluate RCA, update CAPA actions, and provide additional evidence before resubmission. This ensures issues cannot be prematurely closed and reinforces accountability.",
        start: 99.12,
        end: 111.4,
      },
      {
        name: "closure",
        label: "FOS Closure Feedback & Recordkeeping",
        title: "FOS Closure Feedback & Recordkeeping",
        description: "Once the complainant confirms full satisfaction, FOS closes the complaint in the system and records detailed closure feedback. This includes a summary of the conversation, the worker's confirmation, and any additional notes relevant to future monitoring or reporting. All closure data is preserved in the system's digital archive, contributing to grievance trend analysis, HRDD indicators, and long-term risk prevention insights.",
        start: 111.4,
        end: 120,
      },
    ],
  },
  module4: {
    id: "module4",
    title: "Dashboards & Risk Insights",
    scenes: [
      {
        name: "intro",
        label: "Overview",
        title: "Dashboards & Risk Insights",
        description: "Data Intelligence for HRDD reporting and risk monitoring.",
        start: 0,
        end: 16,
      },
      {
        name: "breakdown",
        label: "Real-Time Case Overview",
        title: "Real-Time Case Overview",
        description: "Provides a dynamic view of total, open, in-process, closed, and overdue complaints, enhancing operational transparency and enabling timely decision-making.",
        start: 16,
        end: 30.64,
      },
      {
        name: "heatmap",
        label: "Category-Based Analytics",
        title: "Category-Based Analytics",
        description: "Segments complaints by HRDD-relevant categories such as wages and benefits, harassment, discrimination, Health safety & Environment, and working hours to facilitate targeted interventions.",
        start: 30.64,
        end: 43.4,
      },
      {
        name: "metrics",
        label: "Unit & Department-Level Insights",
        title: "Unit & Department-Level Insights",
        description: "Visualizes risk concentration through breakdowns across units, shifts, or departments, highlighting priority areas for action.",
        start: 43.4,
        end: 59.4,
      },
      {
        name: "timeline",
        label: "RCA & CAPA Performance Metrics",
        title: "RCA & CAPA Performance Metrics",
        description: "Evaluates investigation quality, CAPA completion rates, adherence to deadlines, and recurrence rates to measure overall operational effectiveness.",
        start: 59.4,
        end: 70.4,
      },
      {
        name: "nps",
        label: "Worker Satisfaction Indicators",
        title: "Worker Satisfaction Indicators",
        description: "Aggregates feedback from verification calls to assess the effectiveness of remediation processes and overall worker happiness & Safety scores.",
        start: 70.4,
        end: 75.68,
      },
      {
        name: "trends",
        label: "Trend Analysis & Date-Range Filters",
        title: "Trend Analysis & Date-Range Filters",
        description: "Enables weekly, monthly, quarterly, and annual trend analysis, allowing for comparative insights and strategic planning.",
        start: 75.68,
        end: 90.28,
      },
      {
        name: "export",
        label: "Exportable Compliance Reports",
        title: "Exportable Compliance Reports",
        description: "Supports report exports for HRDD, ESG, and CSDDD compliance, including due diligence reporting, social compliance audits, internal dashboards, and brand reporting.",
        start: 90.28,
        end: 102,
      },
    ],
  },
}